apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: mortgage-rate
  name: mortgage-rate
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mortgage-rate
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mortgage-rate
    spec:
      containers:
      - image: sakthiece08/mortgage-rate-service:0.0.12-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: mortgage-rate-service
        readinessProbe:
          httpGet:
            port: 8100
            path: /actuator/health/readiness
        livenessProbe:
          httpGet:
            port: 8100
            path: /actuator/health/liveness    
      restartPolicy: Always
      
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: mortgage-rate
  name: mortgage-rate
  namespace: default
spec:
  ports:
  - port: 8100
    protocol: TCP
    targetPort: 8100
  selector:
    app: mortgage-rate
  sessionAffinity: None
  type: LoadBalancer  
